.PHONY: clean All

All:
	@echo "----------Building project:[ 1_basic_variables_and_primitive_types - Debug ]----------"
	@cd "1_basic_variables_and_primitive_types" && "$(MAKE)" -f  "1_basic_variables_and_primitive_types.mk"
clean:
	@echo "----------Cleaning project:[ 1_basic_variables_and_primitive_types - Debug ]----------"
	@cd "1_basic_variables_and_primitive_types" && "$(MAKE)" -f  "1_basic_variables_and_primitive_types.mk" clean
