.PHONY: clean All

All:
	@echo "----------Building project:[ room_cleaning_price - Debug ]----------"
	@cd "room_cleaning_price" && "$(MAKE)" -f  "room_cleaning_price.mk"
clean:
	@echo "----------Cleaning project:[ room_cleaning_price - Debug ]----------"
	@cd "room_cleaning_price" && "$(MAKE)" -f  "room_cleaning_price.mk" clean
