.PHONY: clean All

All:
	@echo "----------Building project:[ basic_operation_challenge - Debug ]----------"
	@cd "basic_operation_challenge" && "$(MAKE)" -f  "basic_operation_challenge.mk"
clean:
	@echo "----------Cleaning project:[ basic_operation_challenge - Debug ]----------"
	@cd "basic_operation_challenge" && "$(MAKE)" -f  "basic_operation_challenge.mk" clean
