.PHONY: clean All

All:
	@echo "----------Building project:[ 1_arrays - Debug ]----------"
	@cd "1_arrays" && "$(MAKE)" -f  "1_arrays.mk"
clean:
	@echo "----------Cleaning project:[ 1_arrays - Debug ]----------"
	@cd "1_arrays" && "$(MAKE)" -f  "1_arrays.mk" clean
