.PHONY: clean All

All:
	@echo "----------Building project:[ 4_scope_and_static_variables - Debug ]----------"
	@cd "4_scope_and_static_variables" && "$(MAKE)" -f  "4_scope_and_static_variables.mk"
clean:
	@echo "----------Cleaning project:[ 4_scope_and_static_variables - Debug ]----------"
	@cd "4_scope_and_static_variables" && "$(MAKE)" -f  "4_scope_and_static_variables.mk" clean
