.PHONY: clean All

All:
	@echo "----------Building project:[ 1_basics - Debug ]----------"
	@cd "1_basics" && "$(MAKE)" -f  "1_basics.mk"
clean:
	@echo "----------Cleaning project:[ 1_basics - Debug ]----------"
	@cd "1_basics" && "$(MAKE)" -f  "1_basics.mk" clean
