.PHONY: clean All

All:
	@echo "----------Building project:[ 8_basic_IO - Debug ]----------"
	@cd "8_basic_IO" && "$(MAKE)" -f  "8_basic_IO.mk"
clean:
	@echo "----------Cleaning project:[ 8_basic_IO - Debug ]----------"
	@cd "8_basic_IO" && "$(MAKE)" -f  "8_basic_IO.mk" clean
