.PHONY: clean All

All:
	@echo "----------Building project:[ 1_example_project - Debug ]----------"
	@cd "1_example_project" && "$(MAKE)" -f  "1_example_project.mk"
clean:
	@echo "----------Cleaning project:[ 1_example_project - Debug ]----------"
	@cd "1_example_project" && "$(MAKE)" -f  "1_example_project.mk" clean
