.PHONY: clean All

All:
	@echo "----------Building project:[ 3_compiler_errors - Release ]----------"
	@cd "3_compiler_errors" && "$(MAKE)" -f  "3_compiler_errors.mk"
clean:
	@echo "----------Cleaning project:[ 3_compiler_errors - Release ]----------"
	@cd "3_compiler_errors" && "$(MAKE)" -f  "3_compiler_errors.mk" clean
