.PHONY: clean All

All:
	@echo "----------Building project:[ 1_basic_classes - Debug ]----------"
	@cd "1_basic_classes" && "$(MAKE)" -f  "1_basic_classes.mk"
clean:
	@echo "----------Cleaning project:[ 1_basic_classes - Debug ]----------"
	@cd "1_basic_classes" && "$(MAKE)" -f  "1_basic_classes.mk" clean
