.PHONY: clean All

All:
	@echo "----------Building project:[ 2_constructors_and_deconstructors - Debug ]----------"
	@cd "2_constructors_and_deconstructors" && "$(MAKE)" -f  "2_constructors_and_deconstructors.mk"
clean:
	@echo "----------Cleaning project:[ 2_constructors_and_deconstructors - Debug ]----------"
	@cd "2_constructors_and_deconstructors" && "$(MAKE)" -f  "2_constructors_and_deconstructors.mk" clean
