.PHONY: clean All

All:
	@echo "----------Building project:[ 3_mixed_expressions_and_conversions - Debug ]----------"
	@cd "3_mixed_expressions_and_conversions" && "$(MAKE)" -f  "3_mixed_expressions_and_conversions.mk"
clean:
	@echo "----------Cleaning project:[ 3_mixed_expressions_and_conversions - Debug ]----------"
	@cd "3_mixed_expressions_and_conversions" && "$(MAKE)" -f  "3_mixed_expressions_and_conversions.mk" clean
