.PHONY: clean All

All:
	@echo "----------Building project:[ 2_operators - Debug ]----------"
	@cd "2_operators" && "$(MAKE)" -f  "2_operators.mk"
clean:
	@echo "----------Cleaning project:[ 2_operators - Debug ]----------"
	@cd "2_operators" && "$(MAKE)" -f  "2_operators.mk" clean
