.PHONY: clean All

All:
	@echo "----------Building project:[ 6_pointer_and_functions - Debug ]----------"
	@cd "6_pointer_and_functions" && "$(MAKE)" -f  "6_pointer_and_functions.mk"
clean:
	@echo "----------Cleaning project:[ 6_pointer_and_functions - Debug ]----------"
	@cd "6_pointer_and_functions" && "$(MAKE)" -f  "6_pointer_and_functions.mk" clean
