.PHONY: clean All

All:
	@echo "----------Building project:[ 4_arrays_pointers_and_pointer_arithmetics - Debug ]----------"
	@cd "4_arrays_pointers_and_pointer_arithmetics" && "$(MAKE)" -f  "4_arrays_pointers_and_pointer_arithmetics.mk"
clean:
	@echo "----------Cleaning project:[ 4_arrays_pointers_and_pointer_arithmetics - Debug ]----------"
	@cd "4_arrays_pointers_and_pointer_arithmetics" && "$(MAKE)" -f  "4_arrays_pointers_and_pointer_arithmetics.mk" clean
