.PHONY: clean All

All:
	@echo "----------Building project:[ 3_dynamic_memory_allocation - Debug ]----------"
	@cd "3_dynamic_memory_allocation" && "$(MAKE)" -f  "3_dynamic_memory_allocation.mk"
clean:
	@echo "----------Cleaning project:[ 3_dynamic_memory_allocation - Debug ]----------"
	@cd "3_dynamic_memory_allocation" && "$(MAKE)" -f  "3_dynamic_memory_allocation.mk" clean
